### ISSUE TITLE
Please include the SDK of x-plane

### ISSUE THREAD

**Issue by chbacheng** [jaurenq/XPNet#9]
Please include the SDK, the source code downloaded after the compilation has been tried many times, have ended in failure.

**Comment by chbacheng** [comment]
All the plug-in files have been compiled successfully, but the plug-in still cannot be loaded on x-plane11. Please refine your example, it will be very helpful to me, thank you!

**Comment by jaurenq** [comment]
I'm not certain I've understood what you're asking, but an attempt to answer:

1. I cannot include the .NET Core SDK or runtime with the download, it's not mine to redistribute.  I _would_ like to put something together that would make it easier to get the SDK installed in the right place for a plugin, and I'm open to ideas of how to do that.

2. The example is working correctly for me and others.  If you'll post your X-Plane log file from an attempt to open X-Plane with the plugin installed, we can help you diagnose whatever you're running across.

**Comment by chbacheng** [comment]
In fact, my requirement is very simple, let me load XpNet plug-in successfully on x-plane, can output the display text on the world screen, can receive and execute the commands passed by the client.
But at the moment, I can't load the XpNet plugin, so I can't do anything about it.
